name: Build smartmontools Linux x64

on:
  push:
    branches: [ phase1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool

      - name: Build smartmontools
        run: |
          ./autogen.sh
          ./configure
          make

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: smartctl-linux-x64
          path: src/smartctl
